# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-30 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('bookname', models.CharField(max_length=20, unique=True)),
                ('press', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 't_book',
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('rname', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 't_reader',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('borrow_data', models.DateField()),
                ('borrow_days', models.IntegerField()),
                ('bookname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
                ('rname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Reader')),
            ],
            options={
                'db_table': 't_record',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 't_type',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('uname', models.CharField(max_length=20)),
                ('psd', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 't_user',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Type'),
        ),
    ]
